apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegeta
  labels:
    app: vegeta
spec:
  replicas: {{ .Values.vegeta.replicas }}
  selector:
    matchLabels:
      app: vegeta
  template:
    metadata:
      labels:
        app: vegeta
    spec:
      containers:
      - name: vegeta
        image: peterevans/vegeta:latest
        command: ["sh", "-c", "while true; do sleep 3600; done"]
        resources:
          limits:
            cpu: {{ .Values.vegeta.resources.limits.cpu }}
            memory: {{ .Values.vegeta.resources.limits.memory }}
          requests:
            cpu: {{ .Values.vegeta.resources.requests.cpu }}
            memory: {{ .Values.vegeta.resources.requests.memory }}
        env:
        - name: PROXY_IP
          value: "{{ .Values.proxy.privateIP }}"
        - name: PROXY_PORT
          value: "{{ .Values.proxy.port }}"
        - name: RPS
          value: "{{ .Values.vegeta.rpsPerGenerator }}"
        - name: DURATION
          value: "{{ .Values.vegeta.duration }}"
        - name: TIMEOUT
          value: "{{ .Values.vegeta.timeout }}"
        - name: MAX_CONNECTIONS
          value: "{{ .Values.vegeta.maxConnections }}"
