apiVersion: v1
kind: Service
metadata:
  name: {{ include "highper-gateway.fullname" . }}
  labels:
    {{- include "highper-gateway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- $ports := index .Values.service.ports .Values.useCase }}
    {{- range $ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
    {{- if $.Values.metrics.enabled }}
    - name: metrics
      port: {{ $.Values.metrics.port }}
      targetPort: {{ $.Values.metrics.port }}
      protocol: TCP
    {{- end }}
    {{- if $.Values.health.enabled }}
    - name: health
      port: {{ $.Values.health.port }}
      targetPort: {{ $.Values.health.port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "highper-gateway.selectorLabels" . | nindent 4 }}
