#!/bin/bash
# OS Tuning Script for Tier 3 Performance (50K req/s)
# Run with: sudo ./tune-os-for-tier3.sh

set -e

echo "=========================================="
echo "OS Tuning for High-Performance Networking"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Please run with sudo"
    echo "Usage: sudo $0"
    exit 1
fi

echo "Applying TCP/IP kernel parameters..."
echo ""

# Increase ephemeral port range
echo "1. Expanding ephemeral port range: 32768-60999 → 1024-65535"
sysctl -w net.ipv4.ip_local_port_range="1024 65535"

# Reduce TIME_WAIT timeout
echo "2. Reducing TCP FIN timeout: 60s → 15s"
sysctl -w net.ipv4.tcp_fin_timeout=15

# Enable TCP port reuse
echo "3. Enabling TCP TIME_WAIT reuse"
sysctl -w net.ipv4.tcp_tw_reuse=1

# Enable TCP timestamps (required for tw_reuse)
echo "4. Enabling TCP timestamps"
sysctl -w net.ipv4.tcp_timestamps=1

# Increase connection backlog
echo "5. Increasing connection backlog: 4096 → 65535"
sysctl -w net.core.somaxconn=65535

# Increase network device backlog
echo "6. Increasing netdev backlog: default → 5000"
sysctl -w net.core.netdev_max_backlog=5000

# Additional optimizations
echo "7. Optimizing TCP keepalive"
sysctl -w net.ipv4.tcp_keepalive_time=600
sysctl -w net.ipv4.tcp_keepalive_intvl=60
sysctl -w net.ipv4.tcp_keepalive_probes=3

echo ""
echo "✅ OS tuning applied successfully!"
echo ""

# Display current settings
echo "=========================================="
echo "Current Kernel Parameters"
echo "=========================================="
echo ""
echo "Ephemeral ports:    $(sysctl -n net.ipv4.ip_local_port_range)"
echo "TCP FIN timeout:    $(sysctl -n net.ipv4.tcp_fin_timeout)s"
echo "TCP TW reuse:       $(sysctl -n net.ipv4.tcp_tw_reuse)"
echo "TCP timestamps:     $(sysctl -n net.ipv4.tcp_timestamps)"
echo "somaxconn:          $(sysctl -n net.core.somaxconn)"
echo "netdev_backlog:     $(sysctl -n net.core.netdev_max_backlog)"
echo ""

# Calculate theoretical max connections/sec
PORTS=$(sysctl -n net.ipv4.ip_local_port_range | awk '{print $2 - $1}')
TIMEOUT=$(sysctl -n net.ipv4.tcp_fin_timeout)
MAX_CONN_SEC=$((PORTS / TIMEOUT))

echo "=========================================="
echo "Theoretical Capacity"
echo "=========================================="
echo ""
echo "Available ports:    $PORTS"
echo "TIME_WAIT duration: ${TIMEOUT}s"
echo "Max new conn/sec:   ~${MAX_CONN_SEC} (without keep-alive)"
echo "With keep-alive:    50K+ req/s achievable ✓"
echo ""

# Offer to make permanent
echo "=========================================="
echo "Make Changes Permanent?"
echo "=========================================="
echo ""
read -p "Do you want to make these changes permanent across reboots? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Creating /etc/sysctl.d/99-high-performance.conf..."

    cat > /etc/sysctl.d/99-high-performance.conf <<EOF
# High-Performance Networking Tuning
# Generated by tune-os-for-tier3.sh
# Date: $(date)

# Ephemeral port range
net.ipv4.ip_local_port_range = 1024 65535

# TCP timeouts
net.ipv4.tcp_fin_timeout = 15

# TCP reuse
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_timestamps = 1

# Connection backlog
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 5000

# TCP keepalive
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 60
net.ipv4.tcp_keepalive_probes = 3
EOF

    chmod 644 /etc/sysctl.d/99-high-performance.conf
    echo "✅ Changes saved to /etc/sysctl.d/99-high-performance.conf"
    echo "   Settings will persist across reboots"
else
    echo "⚠️  Changes are temporary (will reset on reboot)"
    echo "   Run this script again and choose 'y' to make permanent"
fi

echo ""
echo "=========================================="
echo "✅ OS Tuning Complete!"
echo "=========================================="
echo ""
echo "You can now proceed with Tier 3 load testing:"
echo "  - Target: 50K req/s"
echo "  - Expected p99: < 25ms"
echo "  - Client capacity: ~4,266 new conn/s (vs 470 before)"
echo ""
echo "Next steps:"
echo "  1. Return to Claude Code"
echo "  2. Confirm tuning is complete"
echo "  3. Begin Tier 3 testing"
echo ""
