apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegeta
  labels:
    app: vegeta
spec:
  replicas: {{ .Values.vegeta.replicas }}
  selector:
    matchLabels:
      app: vegeta
  template:
    metadata:
      labels:
        app: vegeta
    spec:
      containers:
      - name: vegeta
        image: {{ .Values.vegeta.image }}:{{ .Values.vegeta.tag }}
        command: ["sh", "-c", "while true; do sleep 3600; done"]
        resources:
          limits:
            cpu: {{ .Values.vegeta.resources.limits.cpu }}
            memory: {{ .Values.vegeta.resources.limits.memory }}
          requests:
            cpu: {{ .Values.vegeta.resources.requests.cpu }}
            memory: {{ .Values.vegeta.resources.requests.memory }}
